config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  resources :sessions, only: [:new, :create,:destroy]
  resources :users, only: [:new, :create, :show, :edit, :update,:destroy]
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tasks , dependent: :destroy
    validates :name, presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 }, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation { email.downcase! }
    has_secure_password
    validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base  
    include SessionsHelper
    before_action :login_required

    private
    def login_required
        redirect_to new_session_path unless current_user
        flash[:notice] = "Veuillez vous connecter"
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to user_path(user.id) , notice: "J'ai réussi à me connecter"
      else
        flash[:danger] = "Il y a une erreur dans votre adresse e-mail ou votre mot de passe"
        render :new
      end
    end

  def destroy
    session.delete(:user_id)
      flash[:notice] = 'Vous avez été déconnecté.'
      redirect_to new_session_path
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  def index
    @tasks = current_user.tasks
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to tasks_path, notice: t('.created')
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: t('.updated')
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: t('.destroyed')
  end

  private

    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :correct_user, only: [:show]
    skip_before_action :login_required, only: [:new, :create]
    def new
        @user=User.new
    end
  
    def create
        @user = User.new(user_params)
        if @user.save
        log_in(@user)
        redirect_to user_path(@user.id) , notice: "J'ai réussi à créer un compte"
        else
        render :new
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_path(@user), notice: "J'ai mis à jour mon compte"
        else
            render :edit
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to new_session_path, notice: "L'utilisateur a été supprimé avec succès."
    end
      


    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
        @user = User.find(params[:id])
        redirect_to current_user unless current_user?(@user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def logged_in?
        current_user.present?
    end

    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user?(user)
        user == current_user
    end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CdpWebRailsSessionLoginTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
    <ul>
    <li><%= link_to "Task column", tasks_path%></li>
    <li><%= link_to "Register a task", new_task_path %></li>
    <li><%= link_to "Account", user_path(current_user.id) %></li>
    <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
    </ul>
    <% else %>
    <ul>
    <li><%= link_to "Account registration", new_user_path %></li>
    <li><%= link_to "Login", new_session_path %></li>
    </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

    

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', task: @task %>

<%= link_to t('common.show'), @task %> |
<%= link_to t('common.back'), tasks_path %>

app/views/tasks/index.html.erb
<h1><%= t('.title') %></h1>

<table>
  <thead>
    <tr>
      <th><%= Task.human_attribute_name(:title) %></th>
      <th><%= Task.human_attribute_name(:content) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= link_to t('common.show'), task %></td>
        <td><%= link_to t('common.edit'), edit_task_path(task) %></td>
        <td><%= link_to t('common.destroy'), task, method: :delete, data: { confirm: t('common.confirm_destroy') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('common.new'), new_task_path %>

app/views/tasks/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', task: @task %>

<%= link_to t('common.back'), tasks_path %>

app/views/tasks/show.html.erb
<h1><%= t('.title') %></h1>

<p>
  <strong><%= Task.human_attribute_name(:title) %>:</strong>
  <%= @task.title %>
</p>

<p>
  <strong><%= Task.human_attribute_name(:content) %>:</strong>
  <%= @task.content %>
</p>

<%= link_to t('common.edit'), edit_task_path(@task) %> |
<%= link_to t('common.back'), tasks_path %>

app/views/users/edit.html.erb
<h1>Edit User</h1>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with(model: @user, local: true) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %> 
    <%= f.password_field :password %> 

    <%= f.label :password_confirmation %> 
    <%= f.password_field :password_confirmation %> 
    <ul>
    <%= f.submit "Save Changes" %>
    </ul>
  <% end %>

  <%= link_to t('Return'),@user%>
    

app/views/users/new.html.erb
<h1>Sign up</h1> 
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
 <%= form_with(model: @user, local: true) do |f| %> 
 <%= f.label :name %> 
 <%= f.text_field :name %> 
 <%= f.label :email %> 
 <%= f.email_field :email %> 
 <%= f.label :password %> 
 <%= f.password_field :password %> 
 <%= f.label :password_confirmation %> 
 <%= f.password_field :password_confirmation %> 
 <%= f.submit "Create my account" %> 
 <% end %>

app/views/users/show.html.erb
<h1>Account details page</h1> 
<h2>Nom &nbsp<%= @user.name %> </h2>
<p>Email adress &nbsp<%= @user.email %></ul></p>
<%= link_to ('Edit'), edit_user_path(@user) %> |
<%= link_to ('Delete'), user_path(@user), method: :delete,data: { confirm: 'Êtes-vous sûr de vouloir supprimer cet utilisateur ?' } %>